### ISSUE TITLE
增加听写功能

### ISSUE THREAD

**Issue by lishuaifu** [Benature/WordReview#10]
**功能描述**

可以实现对单词的听写功能，包括通过英语写汉语意思，通过汉语拼写英语单词
**希望这个功能可以解决：**（可选）

形成单词记忆，更容易测试自己的记忆能力。
**额外的信息**（可选）
任何其他的您认为能描述该功能的信息。

**Comment by Benature** [comment]
参见[快捷键](https://github.com/Benature/WordReview#%E5%BF%AB%E6%8D%B7%E9%94%AE)中的`输入模式`，快捷键<kbd>I</kbd>

进入背单词页面后点击<kbd>I</kbd>进入输入模式，可以在原先现实单词的位置进行拼写输入，输入完成后会判断拼写是否正确
