### ISSUE TITLE
导入一直失败

### ISSUE THREAD

**Issue by AndreaWWW** [Benature/WordReview#12]
**描述问题**
请简明阐述您的问题 导入数据库一直失败 显示UNIQUE constraint failed: books.BOOK_zh 

**截图：**（可选）  
合适的话可以提供用以描述问题的截图。但是不推荐用截图来展示命令行输出，除非你真的认为这很有必要。

![image](https://user-images.githubusercontent.com/69420313/89730569-56773000-da72-11ea-9e75-a407b16a48a2.png)

**操作环境（请提供以下完整数据）：**  

- 操作系统：windows
- 使用方式： 可执行文件（即在 release 页面下载的）
- 可执行文件版本（若是）：如 0.2.1
- 数据库类型：sqlite（默认） 
- 浏览器： Edge

**Comment by Benature** [comment]
`UNIQUE constraint failed: books.BOOK_zh`：存在多次导入相同书名的情况，即书名不能是一样的。

如果是要重复导入一本书，（不熟悉数据库操作的话）建议删掉`db.sqlite3`，重新放一个新的`db.sqlite3`文件。（**删掉`db.sqlite3`将删除之前导入的所有资料**）
