### ISSUE TITLE
进度-100%什么情况？

### ISSUE THREAD

**Issue by lsy641** [Benature/WordReview#19]
![image](https://user-images.githubusercontent.com/26696711/114315738-d6d6bf00-9b32-11eb-944d-f2cd7e881913.png)
![image](https://user-images.githubusercontent.com/26696711/114315752-e6ee9e80-9b32-11eb-9a07-9e0280144a20.png)

**Comment by Benature** [comment]
这种情况好像我第一次见，可以看看这些地方有没有报错
- 浏览器的 console
- 命令行

另外看起来数据库也可能有问题，导入模板数据的时候会有这种问题吗

**Comment by xunxiangke** [comment]
![Screenshot_2022-05-07-00-05-52-394_com android chrome](https://user-images.githubusercontent.com/26166045/167170521-f0cbbe18-7419-4b53-8e0f-122e4cb2b7e5.jpg)
我也有这个现象😂

**Comment by Benature** [comment]
> 这种情况好像我第一次见，可以看看这些地方有没有报错
> 
> * 浏览器的 console
> * 命令行
> 
> 另外看起来数据库也可能有问题，导入模板数据的时候会有这种问题吗

@xunxiangke 哈喽，可以提供一些相关信息嘛

**Comment by Benature** [comment]
-100%应该已被解决，如仍存在相关问题，欢迎随时re-open该issue
