### ISSUE TITLE
Brilliant project! Can you add crawler component to fetch data from online dicts?

### ISSUE THREAD

**Issue by Anarion-zuo** [Benature/WordReview#2]

**Comment by Benature** [comment]
Yeah, that is a good suggestion and it lies in my TODO list for a long time. However, CORS (Cross-Origin Resource Sharing) is a problem that I cannot handle it for now.

Recently I have written a [Chrome extension](https://github.com/Benature/WordReview/tree/ben/ChromeExtension) which can avoid the limitation of CORS and get data from other sites.

BTW, I am not sure what you mean with the `online dicts`, here is two my understandings:
1. you have a specific list of words and you want to fetch some data like meaning, phonetic symbol, example sentences, etc..
2. you want to get a list words from other sites.

**Comment by Benature** [comment]
And as the back-end is written by python, it is very easy to add an API to run a python crawler, which you are skilled in, I think.

**Comment by Benature** [comment]
> And as the back-end is written by python, it is very easy to add an API to run a python crawler, which you are skilled in, I think.

done in [6790a67](https://github.com/Benature/WordReview/commit/6790a6770356dfcdafbbd190e0c8ae79e17e162b)
