### ISSUE TITLE
对于小白的与预备说明无法访问

### ISSUE THREAD

**Issue by Kid-Janlon** [Benature/WordReview#25]
- [x] 我已阅读[READEME.md](https://github.com/Benature/WordReview/blob/ben/README.md)中的[问题自检](https://github.com/Benature/WordReview/blob/ben/README.md#%E9%97%AE%E9%A2%98%E8%87%AA%E6%A3%80)

**描述问题**
请简明阐述您的问题

**复现问题**
复现问题的步骤:

1. 
2. 

```
请将报错信息复制到此处
```

**截图：**（可选）

**操作环境（请提供以下完整数据）：**

- 操作系统：mac / windows
- 使用方式：源码 / 可执行文件（即在 release 页面下载的）
- 可执行文件版本（若是）：如 0.2.0
- 数据库类型：sqlite（默认） / mysql
- 浏览器：Chrome / Firefox / Edge / etc.

**额外信息：**（可选）  
任何其他的您认为有助于能描述问题/解决问题的信息。

**Comment by Benature** [comment]
链接已更新
