### ISSUE TITLE
我是一个小新手  想问一下怎么安装呀

### ISSUE THREAD

**Issue by chuyinmm** [Benature/WordReview#27]
/

**Comment by chuyinmm** [comment]
大佬写的有点看不懂  我只下载了一个anaconda软件之后就不明白了

**Comment by Benature** [comment]
啊 你就这么说我也不知道你哪不懂呀🤦‍♂️

**Comment by guojiw** [comment]
你在问我吗？












啦啦啦
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月25日(周五) 下午3:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Benature/WordReview] 我是一个小新手  想问一下怎么安装呀 (Issue #27)




 
大佬写的有点看不懂  我只下载了一个anaconda软件之后就不明白了

**Comment by chuyinmm** [comment]
对的&nbsp; 就是我打包下载了 然后就不知道怎么安装之类的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Benature/WordReview"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月4日(星期一) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Benature/WordReview] 我是一个小新手  想问一下怎么安装呀 (Issue #27)





 你在问我吗？ 
 
 
 
 
 
 
 
 
 
 
 
 
 啦啦啦 
 ***@***.*** 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年3月25日(周五) 下午3:18 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: Re: [Benature/WordReview] 我是一个小新手  想问一下怎么安装呀 (Issue #27) 
 
 
 
 
   
 大佬写的有点看不懂  我只下载了一个anaconda软件之后就不明白了

**Comment by guojiw** [comment]
加我吧,qq:483154542












啦啦啦
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月4日(周一) 上午10:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Benature/WordReview] 我是一个小新手  想问一下怎么安装呀 (Issue #27)




 对的&amp;nbsp; 就是我打包下载了 然后就不知道怎么安装之类的 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Benature/WordReview"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年4月4日(星期一) 上午10:16 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Benature/WordReview] 我是一个小新手  想问一下怎么安装呀 (Issue #27) 
 
 
 
 
 
  你在问我吗？  
   
   
   
   
   
   
   
   
   
   
   
   
  啦啦啦  
  ***@***.***  
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2022年3月25日(周五) 下午3:18  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: Re: [Benature/WordReview] 我是一个小新手  想问一下怎么安装呀 (Issue #27)  
   
   
   
   
     
  大佬写的有点看不懂  我只下载了一个anaconda软件之后就不明白了
