### ISSUE TITLE
数据导入出错了请问是什么原因呢

### ISSUE THREAD

**Issue by yuhe028** [Benature/WordReview#30]
感谢您的分享
想请问一下网页导入那个notion的权限是失效了吗（好像打不开诶）
还有请教一下在导入数据库后出现"TypeError: Object of type 'SSLError' is not JSON serializable"这个原因是因为什么呢？

**Comment by Benature** [comment]
>想请问一下网页导入那个notion的权限是失效了吗（好像打不开诶）

谢谢提醒，链接已更新： <https://www.notion.so/benature/Word-Review-fa8ddbab5afa43278e2005ce8b7b9a2a>

>还有请教一下在导入数据库后出现"TypeError: Object of type 'SSLError' is not JSON serializable"这个原因是因为什么呢？

这个可以给出报错上下文吗，单一句我不好定位是哪里的异常哦

**Comment by Benature** [comment]
该issue长时间未活跃暂时close，提问者如果有更新情况欢迎随时open该issue。 :)
