### ISSUE TITLE
在打开的时候，直接弹出http://127.0.0.1:8000/

### ISSUE THREAD

**Issue by yue-yin** [Benature/WordReview#4]
小细节，只是觉得这样更方便，不用自己复制粘贴
啊……我就是指望它更傻瓜

**Comment by Benature** [comment]
更新代码后在`config.py`里面多加一行命令就可以了

```python
auto_open_browser = True
```

done in [9e79895](https://github.com/Benature/WordReview/commit/36607704c87ad17bcc28b91db5c30a465fbcd90f)

**Comment by Benature** [comment]
目前我只在 mac 上面测试过可以在默认浏览器打开，但是不太确定这部分代码会不会和系统有关，如果有 windows 的用户可以反映一下是否成功自动打开浏览器吗？

**Comment by yue-yin** [comment]
我也是mac所以……

**Comment by Benature** [comment]
- [x] Windows checked √
