### ISSUE TITLE
请问浏览器插件WordReview是不是没有了

### ISSUE THREAD

**Issue by World-Homeostasis** [Benature/WordReview#41]
已经点星了
- [x] 我已阅读[READEME.md](https://github.com/Benature/WordReview/blob/ben/README.md)中的[问题自检](https://github.com/Benature/WordReview/blob/ben/README.md#%E9%97%AE%E9%A2%98%E8%87%AA%E6%A3%80)

**描述问题**
请问大佬浏览器插件WordReview是不是没有了

**复现问题**
复现问题的步骤:通过edge商店搜索WordReview，以及https://[www.crxsoso.com](https://www.crxsoso.com/?utm=itab)/?utm=itab搜索

**截图：**（可选）

**操作环境（请提供以下完整数据）：**

- 操作系统：windows11
- 使用方式：可执行文件（即在 release 页面下载的）
- 可执行文件版本（若是）： 0.2.1
- 数据库类型：sqlite（默认） / mysql
- 浏览器： Edge

**额外信息：**（可选）  
我是小白，通过网上找到了考研单词的excel文件，但是只有单词和中文解释，想通过浏览器插件爬取助记等

**Comment by Benature** [comment]
插件需要手动安装哦，文件在 https://github.com/Benature/WordReview/tree/ben/extension ，没有正式发布

**Comment by World-Homeostasis** [comment]
> 插件需要手动安装哦，文件在 https://github.com/Benature/WordReview/tree/ben/extension ，没有正式发布

感谢
