### ISSUE TITLE
发音问题

### ISSUE THREAD

**Issue by yue-yin** [Benature/WordReview#5]
总感觉单词的发音很不标准，特别是abandon，你可以自己听一下。
这是从哪儿来的音频……是不是要换个地方获取比较好

**Comment by Benature** [comment]
确实是会有点不标准😅  

这个语音是 HTML5 语音合成的，文档在[这里](http://s0developer0mozilla0org.icopy.site/en-US/docs/Web/API/SpeechSynthesisUtterance)。  
当时找到比较速成的就这个方法所以就先用了🤦‍♂️

**Comment by Benature** [comment]
现在换成了百度的 API，你可以试试看会不会好点。

现在默认使用百度的语音合成，原来旧的那种语音合成其实是在电脑本地合成的，所以不同电脑听到的效果还会有所差异（比如我听到的是男声我同学听到的是女声）

先关了，有问题再开

**Comment by yue-yin** [comment]
哈哈，是真的好多了
