### ISSUE TITLE
部分功能未能实现：单词标记、例句的关键词高亮、记忆法笔记拆解

### ISSUE THREAD

**Issue by Sirius-cyber** [Benature/WordReview#7]
**描述问题**
1.单词复习页面未能出现单词标记（可勾选的“重难词、已掌握、太简单”）
2.例句的关键词高亮未能出现
3.记忆法笔记拆解未能出现（截图里的adjoin在词汇之沙网站里面能查到拆解：

```
a(=to)+join(加入):加入到某一群体旁-【邻接】【毗连】
贴近；毗连(ad+join参加→参加在一起→贴近)
```
因此应该不是单词没拆解的问题。

4.界面显示位置似乎有点问题
**截图：**

![微信图片_20200427104458](https://user-images.githubusercontent.com/64355519/80329221-37161780-8874-11ea-813d-aa5385bfdca3.png)
（1 2 3 4 均在以上截图里）

5.艾宾浩斯日历是要自己修改代码来实现吗？

![微信图片_20200427105441](https://user-images.githubusercontent.com/64355519/80329655-97598900-8875-11ea-9abc-dddfcfe0ec49.png)
 

**操作环境：**  

- 操作系统：windows
- 使用方式：源码 
- 数据库类型：sqlite（默认）
- 浏览器：chrome

**Comment by Benature** [comment]
1. 需要在浏览器按下<kbd>F12</kbd>然后点击`console`控制台看一下，应该是有报错导致渲染失败。
2. 下方显示的单词信息（包括例句）是后端自动爬取的例句，这种情况发生在数据库自身没有存储例句的时候（当然，网页导入单词的时候也没有提供这个导入🤦‍♂️），如果你准备的 excel 文件里面包含例句的话可以先告诉你怎么更新数据库应应急
3. 记忆法拆解建议参照[这种语法](https://github.com/Benature/WordReview#%E8%AF%8D%E6%A0%B9%E8%AF%8D%E7%BC%80%E8%AF%8D%E6%BA%90%E6%8B%86%E8%AF%8D%E6%B8%B2%E6%9F%93)，如下。记忆之沙的文本格式不太统一，目前还不能面面俱到。

```
ad=to
join=加入
```

4. 不太确定是不是 get 到，是指 adjoin 下面空白太多了吗？感觉这和问题1 相关，需要看下报错。
5. 艾宾浩斯日历是当你背了一个 list 之后，即背到了某个 list 的最后一个单词，声音上应该会有`mission complete`，然后在日历上会显示这里 List 接下来是那几天需要复习，如果 list 没有背过是不会在日历上显示的。

**Comment by Sirius-cyber** [comment]
好的，艾宾浩斯日历get到了，看报错好像是反爬了。
目前出现以下报错
```
Failed to load resource: the server  font-awesome.min.css:1 responded with a status of 404 (Not Found)`
```
```
复制失败
copy2Clipboard | @ | util.js:14
-- | -- | --
  | renderWord | @ | review.js:258
  | (anonymous) | @ | review.js:679
  | dispatch | @ | jquery-3.4.1.min.js:2
  | v.handle | @ | jquery-3.4.1.min.js:2
  | trigger | @ | jquery-3.4.1.min.js:2
  | (anonymous) | @ | jquery-3.4.1.min.js:2
  | each | @ | jquery-3.4.1.min.js:2
  | each | @ | jquery-3.4.1.min.js:2
  | trigger | @ | jquery-3.4.1.min.js:2
  | k.fn.<computed> | @ | jquery-3.4.1.min.js:2
  | (anonymous) | @ | review.js:397
  | each | @ | jquery-3.4.1.min.js:2
  | each | @ | jquery-3.4.1.min.js:2
  | (anonymous) | @ | review.js:395
  | c | @ | jquery-3.4.1.min.js:2
  | fireWith | @ | jquery-3.4.1.min.js:2
  | l | @ | jquery-3.4.1.min.js:2
  | (anonymous) | @ | jquery-3.4.1.min.js:2
  | load (async) |   |  
  | send | @ | jquery-3.4.1.min.js:2
  | ajax | @ | jquery-3.4.1.min.js:2
  | (anonymous) | @ | review.js:382
  | e | @ | jquery-3.4.1.min.js:2
  | t | @ | jquery-3.4.1.min.js:2
  | setTimeout (async) |   |  
  | (anonymous) | @ | jquery-3.4.1.min.js:2
  | c | @ | jquery-3.4.1.min.js:2
  | fireWith | @ | jquery-3.4.1.min.js:2
  | fire | @ | jquery-3.4.1.min.js:2
  | c | @ | jquery-3.4.1.min.js:2
  | fireWith | @ | jquery-3.4.1.min.js:2
  | ready | @ | jquery-3.4.1.min.js:2
  | B | @ | jquery-3.4.1.min.js:2


```
```
 GET http://localhost:8000/static/fontawesome/font-awesome.min.css net::ERR_ABORTED 404 (Not Found)
```

**Comment by Benature** [comment]
>`GET http://localhost:8000/static/fontawesome/font-awesome.min.css net::ERR_ABORTED 404 (Not Found)`

OK, I get it. 是我路径写错了🤦‍♂️

修正已在仓库更新了，请更新一下

**Comment by Sirius-cyber** [comment]
ok

**Comment by Sirius-cyber** [comment]
好的，记忆法笔记拆解没有正常显示在单词右方（下图是从推送里截的）
![image](https://user-images.githubusercontent.com/64355519/80366706-46b94e80-88bc-11ea-8326-e34ae3593552.png)
html报错
`复制失败 
copy2Clipboard @ util.js:14
`

**Comment by Benature** [comment]
>2.例句的关键词高亮未能出现

新版本已支持<http://dict.cn/mini.php>数据的关键字高亮（红字）

**Comment by Sirius-cyber** [comment]
> > 2.例句的关键词高亮未能出现
> 
> 新版本已支持http://dict.cn/mini.php数据的关键字高亮（红字）

请问更新源码后可以在直接运行下列两行后，
```
python manage.py makemigrations
python manage.py migrate
```
把之前的数据库文件替换新目录的.sqlite3文件然后继续使用吗？

**Comment by Benature** [comment]
wait a minute, 你说`新目录`，请问你是怎么更新源码的，是用`git`还是在网页重新下了一个压缩包？

**Comment by Sirius-cyber** [comment]
在网页重新下了一个压缩包

**Comment by Benature** [comment]
emmm 首先建议下用`git`命令更新，或者用 GitHub 的 GitHub Desktop 客户端更新，这样不会有新旧文件夹的问题，更新会方便很多。（强推）

---

如果还是用压缩包更新，步骤如下
1. 将旧文件夹下的`db.sqlite`文件复制到新的（更新的）文件夹下（因为仓库内是不含数据库文件的，这点和发行版的压缩包不同）
2. 运行命令
```shell
python manage.py makemigrations
python manage.py migrate
```
此时数据库文件和最新版代码匹配，可以正常使用了。

（多说一句，大部分情况甚至可以不跑那两个`migrate`的命令，只有当发现网页数据加载异常时候再`migrate`也行，毕竟不是每次更新都会改动数据库结构）

**Comment by Sirius-cyber** [comment]
ok,get
