### ISSUE TITLE
可以麻烦你加一个逆序排序吗

### ISSUE THREAD

**Issue by triflingZ** [Benature/WordReview#9]
对不起我不是码农，完全没有用过GitHub，不知道这样的排版会不会把你看吐
也还没开始用这个软件，不知道所谓的”顺序“是首字母顺序还是导入的单词书的顺序，如果是后者那就不麻烦你啦，我自己找逆序词表就好^o^

**功能描述**
希望可以按照单词的最后字母（而非首字母）进行排序

**希望这个功能可以解决：**
方便大家/我以词性词根背单词

**额外的信息**
例如replicate, complicate, supplicate, duplicate, explicate, prevaricate, fabricate这些词，如果是顺序不会一起出现（或者有很强大”其他前缀+本词词根=词“的功能，也有可能是我不会编程没有想象力），如果是乱序也几乎不可能出现，但是如果可以乱序排列的话，就可以把这一类”说/造“的动词一网打尽。

本零代码经验的人万分感谢这个充满代码的世界和乐于分享代码的你们（已星）

**Comment by Benature** [comment]
`顺序`是按照导入单词书的顺序来排的，也就是导入时候的`LIST`, (`UNIT`), `INDEX`列（以这三组序号排序）

*感谢支持(๑•̀ㅂ•́)و✧*

**Comment by triflingZ** [comment]
好的大佬！感谢大佬！希望本科技白痴+拖延患者能在本周内（？？？）鼓起勇气安装！

**Comment by Benature** [comment]
哈哈哈好的，安装过程如果有问题也欢迎继续来问哦，一起加油哈😆
